name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  push:
    branches: [ master ]  
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
    
      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
    
        with:
         image: shubham1998rathoor/private-repository
         tags: v1, latest
         registry: docker.io
          
