name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Action
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: maven-artifact
          path: ${{ github.workspace }}/target/maven-tomcat.jar
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      -
        uses: actions/download-artifact@v2
        with:
          name: maven-artifact
          path: ${{ github.workspace }}/target/maven-tomcat.jar
      -
        name: Docker build
        run: |
          docker build -t shubham1998rathoor/actions-maven .
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Docker push
        run: |
          docker push shubham1998rathoor/actions-maven
  run:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      -
        name: Pull image
        run: |
          docker pull shubham1998rathoor/actions-maven
      - name: Run container
        run: |
          docker run shubham1998rathoor/actions-maven  
     
