name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Action
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: maven-artifact
          path: ${{ github.workspace }}/target/maven-tomcat.jar
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: actions/download-artifact@v2
        with:
          name: maven-artifact
          path: ${{ github.workspace }}/target/maven-tomcat.jar
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
         
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shubham1998rathoor/private-repository:latest
